-- INSERT INTO users (first_name, last_name, username, password, created_at, profile_picture) VALUES('Samuel', 'Buraga', 'samuelburaga', '1234', NOW(), NULL);
-- SELECT * FROM users
-- SELECT EXISTS (SELECT * FROM users WHERE username = 'samuelburaga' AND password = '1234')